site_name: RESPX
site_description: A utility for mocking out the Python HTTPX library.

theme:
  name: "material"
  palette:
    primary: "deep purple"
    accent: "deep purple"
  icon:
    logo: "material/school"

repo_name: lundberg/respx
repo_url: https://github.com/lundberg/respx
edit_uri: ""

nav:
  - Introduction: "index.md"
  - User Guide: "guide.md"
  - API Reference: "api.md"
  - Test Case Examples: "examples.md"

markdown_extensions:
  - admonition
  - codehilite
  - mkautodoc
