name: docs

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build & Publish
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Cache pip
      uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip
        restore-keys: |
          ${{ runner.os }}-pip
    - name: Cache nox
      uses: actions/cache@v1
      with:
        path: .nox
        key: ${{ runner.os }}-nox
        restore-keys: |
          ${{ runner.os }}-nox
    - name: Build
      run: |
        pip install nox
        nox -s docs
    - name: Publish
      run: |
        git config user.email ${{ secrets.GITHUB_EMAIL }}
        git remote set-url origin https://${{ secrets.GITHUB_USER }}:${{ secrets.GITHUB_TOKEN }}@github.com/lundberg/respx.git
        ./.nox/docs/bin/mkdocs gh-deploy
